services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - 52003:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  
  db-test:
    image: postgres:15
    container_name: postgres-db-test
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - 52004:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: